/**
 * Created by adam on 28.11.17.
 */

export const USER_AUTH_START = 'USER_AUTH_STARTED';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const EXPENSE_FETCH_START = 'EXPENSE_FETCH_START';
export const EXPENSE_FETCH_SUCCESS = 'EXPENSE_FETCH_SUCCESS';
export const EXPENSE_FETCH_FAIL = 'EXPENSE_FETCH_FAIL';

export const EXPENSE_ADD_START = 'EXPENSE_ADD_START';
export const EXPENSE_ADD_FAIL = 'EXPENSE_ADD_FAIL';
export const EXPENSE_ADD_SUCCESS = 'EXPENSE_ADD_SUCCESS';
export const EXPENSE_DELETE_SUCCESS = 'EXPENSE_DELETE_SUCCESS';

